# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Stat 159 Final Project
author: Janise Liang, Eduardo Madrigal, Sheryl Muttath, and Nandita Radhakrishnan
copyright: "2023"
# logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/janiseliang/data102-final-project
  path_to_book: /
  branch: gh-pages

# Add GitHub & Binder buttons
html:
  use_repository_button: true

launch_buttons:
  notebook_interface        : jupyterlab